### ISSUE TITLE
Not Working for me

### ISSUE THREAD

**Issue by nbarkhina** [Idered/typescript-expect-plugin#1]
Please let me know if i'm missing something, I'm on Windows 10 latest VS Code 

![ezgif-6-81df45c27301](https://user-images.githubusercontent.com/10982154/83257776-0aab2f00-a183-11ea-8893-7a4051ac4e27.gif)

**Comment by Idered** [comment]
@nbarkhina Have you switched to workspace version of typescript? 

![](https://camo.githubusercontent.com/e562d0aa9380997c55db35945483042b60aed39c/68747470733a2f2f692e696d6775722e636f6d2f6b4b39426c4d692e676966)

**Comment by nbarkhina** [comment]
Ok, when I removed the Class it started working. Thanks
